---

kube_version: 1.19.4

#offline_registry
k8s_gcr_io: 10.72.220.199:5000
docker_io: 10.72.220.199:5000
quay_io: 10.72.220.199:5000
gcr_io: 10.72.220.199:5000
docker_elastic_co: 10.72.220.199:5000
# Container runtime,
# Supported: docker, nvidia-docker, containerd.
container_runtime: docker
# docker root dir
docker_root_dir: /var/lib/docker
# Container network,
# Supported: calico, flannel.
cni_enable: true
container_network: calico

# Kubernetes HA extra variables.
vip_interface: enp0s3
vip_address: 172.16.35.10
lb_secure_port: 6443

# offline deploy

# Kubernetes extra addons
enable_ingress: false
enable_dashboard: false
enable_logging: false
enable_monitoring: false
enable_metric_server: false